### PR TITLE
List headers as sources

### PR DESCRIPTION
**Pull request by raitraak-rrk**
Visual Studio Intellisense and Resharper have issues recognizing headers from header only project. Proposed solution is to add the headers into the main library based on the option switch. Also this removes an extra target.

### CODE REVIEW

**Comment by raitraak-rrk** [comment]
No idea why the test is failing under Mac. Can it be test machine load issue or too tight timing requirement?

**Comment by gabime** [comment]
why is it better than the current approach (spdlog_headers_for_ide target)?

**Comment by raitraak-rrk** [comment]
I was trying to replicate the issue I had with VS functionality, but am unable to do so after the latest update.. Maybe they actually fixed something for a change  :) 
So the only remaining argument for the PR is one less target. If you are using multiple libraries, the numbers can pile up.
If that's not enough, feel free to reject.
Thanks for the awesome library!

**Comment by gabime** [comment]
That’s good news. Thanks anyway !

**Pull request closed without merging**
