### PR TITLE
Make file_event_handlers an aggregate

### PR DESCRIPTION
**Pull request by espkk**
Just making file_event_handlers an aggregate to allow designated initialization

### CODE REVIEW

**Comment by gabime** [comment]
I think std function is nullptr by default, so even this init is not needed.

**Comment by espkk** [comment]
> I think std function is nullptr by default, so even this init is not needed.

yes indeed, nullptr_t constructor should be exactly the same. I left it so to keep the original explicit manner
But I agree it maybe makes sense to remove it completely

**Comment by gabime** [comment]
Yes. Please remove it and I will merge.

**Comment by espkk** [comment]
> Yes. Please remove it and I will merge.

done already. I think it was a race between my push and my comment here 😆

**Comment by gabime** [comment]
Thanks @espkk

**Pull request merged**
