### PR TITLE
add hourly log

### PR DESCRIPTION
**Pull request by ewanshin**
I've huge daily logs and I can't delete it (at least 6 month) so I suggest save a log file every each hour.

It use 
hourly_file_sink_mt
hourly_file_sink_st

### CODE REVIEW

**Comment by gabime** [comment]
Thanks, i will add it if there is demand.

**Comment by gjvc** [comment]
This is great -- please merge to master, gabime :+1:

**Comment by ldionne** [comment]
Actually, I think what we really need is a way to rotate logs every `<arbitrary duration>`. For example, rotate every `std::chrono::minutes{10}`. I work at a place where there's so much log that a hourly log would be useless; we currently rotate every few minutes or so.

**Comment by gabime** [comment]
@ldionne Sounds that the size based rotating logger is more suitable in this case

**Comment by ldionne** [comment]
I guess you're right (that's what I'm using), but I think the point remains that it would be very easy to extend this PR to support arbitrary time durations.

**Comment by jzakrzewski** [comment]
Is there any chance of this being merged?

**Comment by mmanoj** [comment]
> 

I implemented base sink for minutes, however getting some errors like this while calling the sink.

**Comment by mmanoj** [comment]
> I guess you're right (that's what I'm using), but I think the point remains that it would be very easy to extend this PR to support arbitrary time durations.

https://github.com/gabime/spdlog/issues/2727

**Pull request closed without merging**
