### PR TITLE
Fixed variable name

### PR DESCRIPTION
**Pull request by naddu77**
Changed the variable name from `check_ebugger_present` to `check_debugger_present`.

### CODE REVIEW

**Comment by gabime** [comment]
Thanks, could you also fix the typo in check_debbugger_present_ ?

**Comment by naddu77** [comment]
Of course it is possible.
But, it is a attribute of the class.
In many places, members of classes are appended with `_`.
Shall I fix it though?

**Comment by gabime** [comment]
I mean to fix the double bb in debbuger_, not the underscore

**Comment by naddu77** [comment]
Ah!! OK! I got it.

**Pull request merged**
