### PR TITLE
add callback while rotate the log file

### PR DESCRIPTION
**Pull request by seker**
add callback while rotate the log file

### CODE REVIEW

**Comment by gabime** [comment]
Thanks, whats the use case here?

**Comment by seker** [comment]
> Thanks, whats the use case here?

when rotates the log file ，my app hope to upload pre log file to server.

**Comment by gabime** [comment]
we need to define if the callback  is called after the old file closed or not.. There are use cases you want it to be closed  (e.g. you want to zip and rename). On the other hand sometimes you want it to be open (add last line before the file closes). Here is an example of typical callbacks types (from old [branch](https://github.com/gabime/spdlog/tree/file_event_handlers)):


```c++
struct file_event_handlers 
{
    std::function<void(const filename_t &filename, std::FILE *file_stream)> after_open;
    std::function<void(const filename_t &filename, std::FILE *file_stream)> before_close;
    std::function<void(const filename_t &filename)> after_close;
};
```

I suggest to continue the work of this branch.

**Comment by seker** [comment]
> we need to define if the callback is called after the old file closed or not.. There are use cases you want it to be closed (e.g. you want to zip and rename). On the other hand sometimes you want it to be open (add last line before the file closes). Here is an example of typical callbacks types (from old [branch](https://github.com/gabime/spdlog/tree/file_event_handlers)):
> 
> ```c++
> struct file_event_handlers 
> {
>     std::function<void(const filename_t &filename, std::FILE *file_stream)> after_open;
>     std::function<void(const filename_t &filename, std::FILE *file_stream)> before_close;
>     std::function<void(const filename_t &filename)> after_close;
> };
> ```
> 
> I suggest to continue the work of this branch.

ok，thanks~

**Pull request closed without merging**
