### PR TITLE
Prepare a test to find an installed libspdlog

### PR DESCRIPTION
**Pull request by ClausKlein**
The example should be able to build as a standalone project too if
external libfmt was used.

Require the minimum fmt version with find_package().

Require the minimum spdlog version with find_package() at
standalone example.

### CODE REVIEW

**Comment by gabime** [comment]
I don't want to require 6.1.2. It can be used with older versions too

**Comment by ClausKlein** [comment]
No minimum Version?

**Comment by gabime** [comment]
Not sure what it is

**Comment by ClausKlein** [comment]
Build spdlod with  extern fmt v5.0.0?

**Pull request closed without merging**
