### PR TITLE
Add option to select C++20 std format

### PR DESCRIPTION
**Pull request by Oipo**
A minor change that would help reduce the amount of dependencies in my project.

### CODE REVIEW

**Comment by gabime** [comment]
How does it work? spdlog use fmt:: namespace to do formatting(https://github.com/gabime/spdlog/blob/44e1f9f6829cd8acbfea282d390560452e889aff/include/spdlog/logger.h#L340)

**Comment by Oipo** [comment]
Well, this is embarrassing. Just because the tests compile and run doesn't mean the code path I thought actually got taken...

Moreover, std::format is not even provided by [any of the major compilers](https://en.cppreference.com/w/cpp/compiler_support) (P0645R10).  

Once they do and I have drunk some coffee that day, I'll make a new attempt.

**Comment by Oipo** [comment]
Regarding your question though, perhaps it would be an idea to stick `fmt` in a define and swap it out with `std` when the CMake define is set.

**Comment by gabime** [comment]
No worries, thanks for the attempt . 
The thing is that spdlog use internally some fmt utils that are not part of the standard, so it is not very easy to replace entirely fmt with std (and why would we? fmt is great, and it will take a while until std::format is properly supported by major compilers).

**Comment by Oipo** [comment]
fmt is a great library, don't get me wrong. My day job is working in an enterprise which prefers to keep the amount of dependencies as low as possible. Everything open source we add has to be meticulously added to a database per version, hence the effort.

But if it's (way) more effort to modify spdlog, I'll gladly add fmt to the database as well.

**Pull request closed without merging**
