### PR TITLE
 Added fmt::(w)string_view support.

### PR DESCRIPTION
**Pull request by matt77hias**

### CODE REVIEW

**Comment by matt77hias** [comment]
Related to [Issue](https://github.com/gabime/spdlog/issues/1136)

**Comment by gabime** [comment]
Thanks. Please use spdlog::string_view_t instead

**Comment by matt77hias** [comment]
Ok, but I need to add a `spdlog::wstring_view_t` as well for `wchar_t`.

**Comment by gabime** [comment]
ok

**Pull request closed without merging**
