### PR TITLE
There are too many compiler and clang-tidy warnings 

### PR DESCRIPTION
**Pull request by ClausKlein**
you should change you QA!

### CODE REVIEW

**Comment by gabime** [comment]
I my env(ubuntu c++11) i don't see warnings. What env are you using ?

**Comment by ClausKlein** [comment]
bash-5.0$ clang --version
clang version 9.0.0 (trunk 365158)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /opt/local/libexec/llvm-devel/bin
bash-5.0$ 
ninja -v example_header_only 2>&1 | tee ../build.log

**Comment by gabime** [comment]
Please post the warning. messages.
And anyway, so how all those changes fix the warnings? Those are bunch of un related changes as far as i can see

**Comment by ClausKlein** [comment]
[build.log](https://github.com/gabime/spdlog/files/4201276/build.log)

my changes do not fix any compiler warning.
only the cmakelint warnings are fixed.
you must not merge it, you can use it the ran clang-tidy yourself or build with my makefile as i do

**Comment by gabime** [comment]
ok. thanks for the info

**Comment by ClausKlein** [comment]
Sorry, you are to fast!
[clang-tidy.log](https://github.com/gabime/spdlog/files/4201391/clang-tidy.log)

**Pull request closed without merging**
