### PR TITLE
better numeric_limits<>::max/min fix when using SPDLOG_WCHAR_TO_UTF8_SUPPORT

### PR DESCRIPTION
**Pull request by NukeULater**
NOMINMAX macro doesn't work everytime for some reason

### CODE REVIEW

**Comment by gabime** [comment]
What do you mean doesnt work?

**Comment by NukeULater** [comment]
> What do you mean doesnt work?



> What do you mean doesnt work?

Header only compile was causing issues with that,      even with NOMINMAX defined

**Comment by gabime** [comment]
so why does removing the define fix this?

**Comment by NukeULater** [comment]
> so why does removing the define fix this?

It doesn't, the part where I added the parenthesis around std::numeric_limits::max does, and removed the define because it's unnecessary

**Comment by gabime** [comment]
so lets put it back in, otherwise it might break backward compitability for code that relies on it to be already defined.

**Comment by NukeULater** [comment]
if there is not any other code using min/max not sure what backward compatibility it could break, but i re-added it

**Comment by gabime** [comment]
Thanks @NukeULater. Merged.

**Pull request merged**
