### PR TITLE
V1.x

### PR DESCRIPTION
**Pull request by dust-II**
add compress sink

### CODE REVIEW

**Comment by gabime** [comment]
Thanks. Seems bit out of scope for spdlog, especially since it relies on external command line tool.

**Comment by dust-II** [comment]
Thank you for the trouble. Since I'm not very good at Using Github, I didn't actually plan on pulling requests.

BTW:
This compressed sink was developed by me on a Linux machine. It limits the total size of compressed logs. The elimination rules are 
   // Rotate files: max n is 65535，and n is  loop 1~65535,  This design solves the problem of compressing the log when the machine is powered down
    // log.1.gz -> delete 
    // log.2.gz -> delete
    // log.3.gz 
     ... 
     // log.n.txt

**Comment by dust-II** [comment]
Thank you for the trouble. Since I'm not very good at Using Github, I didn't actually plan on pulling requests.

BTW:
This compressed sink was developed by me on a Linux machine. It limits the total size of compressed logs. The elimination rules are 
   // Rotate files: max n is 65535，and n is  loop 1~65535,  This design solves the problem of compressing the log when the machine is powered down
    // log.1.gz -> delete 
    // log.2.gz -> delete
    // log.3.gz 
     ... 
     // log.n.txt

**Comment by gabime** [comment]
On second thought, using an external compressor has advantages.  It allows one to choose whatever compressor he wants without adding dependencies to spdlog.

**Comment by dust-II** [comment]
Thank you for sharing spdlog and your thoughts on compressed logs

**Pull request closed without merging**
