### PR TITLE
Add logger context support

### PR DESCRIPTION
**Pull request by o2gy84**
See examples and unit-tests.

The main idea is we need something that will not share between loggers.
So, we can create something like hierarchy of loggers.

There is something in common with go-style logging (which is almost perfect).

### CODE REVIEW

**Comment by gabime** [comment]
Thanks. Interesting approach. Seems not thread safe though..

**Comment by o2gy84** [comment]
By the way, we already use this patch into production. And no issues with it.

**Comment by o2gy84** [comment]
So, can I do something to move this patch into the trunk?  
Or we can just close this PR?

**Comment by gabime** [comment]
Lets close this for now. Thanks anyway !

**Pull request closed without merging**
