### PR TITLE
Bump fmtlib to 6.0.0

### LINKED ISSUE #1077: Compiler warning with gcc-9 shipped with Fedora 30
Here is the error.

```
/tmp/cmake/ws/../third_party/spdlog/include/spdlog/fmt/bundled/format.h:3475:55: warning: ISO C++ did not adopt string literal operator templates taking an argument pack of characters [-Wpedantic]
 3475 | FMT_CONSTEXPR internal::udl_formatter<Char, CHARS...> operator""_format() {
      |                                                       ^~~~~~~~
```

If someone has an idea I can help to validate the fix.

### PR DESCRIPTION
**Pull request by tgpfeiffer**
I updated the files in `include/spdlog/fmt/bundled` to match the files in version 6.0.0 of `fmt` and updated `src/fmt.cpp` accordingly.

fixes #1077

### CODE REVIEW

**Comment by gabime** [comment]
Thanks! meged

**Comment by alium** [comment]
I tested build spdlog with fmt6 patch commit e149433a80bd6ac2eb6978011f015392377da2bb
but build failed.
log: https://paste.artixlinux.org/view/95c96747

**Comment by gabime** [comment]
It was fixed already. Please try latest commit

**Comment by alium** [comment]
https://paste.artixlinux.org/view/3a580b74

i use master git version (source "git+https://github.com/gabime/spdlog.git"), but still build failed, same error...

configured with:  cmake ../"$pkgname-$pkgver" \
        -DSPDLOG_BUILD_BENCH=OFF \
        -DSPDLOG_BUILD_EXAMPLES=OFF \
        -DSPDLOG_FMT_EXTERNAL=ON \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib

**Comment by alium** [comment]
yes, you right,  it's fixed now , thanks

**Pull request merged**
