### PR TITLE
rotating file logger callback

### PR DESCRIPTION
**Pull request by asit-dhal**
Hi

I have added callback for rotating file logger. https://github.com/gabime/spdlog/issues/155

Feature implemented

- callback for rotational logger: list of files are notified
- callback for daily file logger: recently closed file is notified

I didn't add open file descriptor because it will expose an open file to the client. It may affect future renaming for long running processes.

Please check this one and let me know if you need any changes.

### CODE REVIEW

**Comment by gabime** [comment]
Thanks. I will consider merging (I am not sure because it contains many changes, add 2 different arguments to the loggers creation, and maybe users can do without it anyway)

**Comment by asit-dhal** [comment]
I will recheck everything and will simplify it and send you a new pull request(if possible).

**Comment by asit-dhal** [comment]
Hi @gabime , do you have any specific suggestion for improvement ?

**Comment by gabime** [comment]
I think it is not very important. Il

In anyway, the exact use case trigger should be defined:
Is it that after a file is closed the user wants to process it? or maybe its the other way around-notify about new file so the user will be able to write some header in it..

**Comment by asit-dhal** [comment]
Ok Thanks

**Pull request closed without merging**
