### PR TITLE
Add SPDLOG_VERSION check support

### PR DESCRIPTION
**Pull request by kegechen**
You can use SPDLOG_VERSION to select the latest spdlog features
where available while falling back to older implementations otherwise.
Using SPDLOG_TO_VERSION() for the value to compare with is recommended.
for Example:
```c++
 void sink_it_(const details::log_msg &msg) override
 {
 #if SPDLOG_VERSION < SPDLOG_TO_VERSION(1,4,0)
     fmt::memory_buffer formatted;
 #else
     memory_buf_t formatted;
 #endif
     sinks::base_sink<Mutex>::formatter_->format(msg, formatted);
     // bala bala...
 }

### CODE REVIEW

**Comment by gabime** [comment]
Thanks. Since the macro by itself doesn't actually check anything, I think it should be named differently, perhaps `SPDLOG_GET_VERSION(..)` or similar.

**Comment by kegechen** [comment]
> Thanks. Since the macro by itself doesn't actually check anything, I think it should be named differently, perhaps `SPDLOG_GET_VERSION(..)` or similar.

https://doc.qt.io/qt-6/qtversionchecks-proxy.html#QT_VERSION_CHECK
that's how Qt is used, but what you say makes sense，I prefer SPDLOG_MAKE_VERSION

**Comment by gabime** [comment]
But now it might confuse users with the make tool :)
How about `SPDLOG_TO_VERSION()` ?

**Comment by kegechen** [comment]
> But now it might confuse users with the make tool :) How about `SPDLOG_TO_VERSION()` ?

done

**Comment by gabime** [comment]
Thanks @kegechen

**Pull request merged**
