### PR TITLE
Bundle fmt 9.1.0's std.h too

### PR DESCRIPTION
**Pull request by eli-b**
And provide a header to include either it or the external fmt's version.

This file was added to fmt in version 9.0.0.

### CODE REVIEW

**Comment by gabime** [comment]
Thanks. Since it is a bundled, should be the exact copy of the original, including the code formatting, which seems to be different.

**Comment by eli-b** [comment]
Sorry. I copy and pasted within my IDE, which might have mangled the
formatting. I'll fix this.

**Comment by eli-b** [comment]
Please review again. I've amended the commit in my branch.

**Comment by gabime** [comment]
Merged. Thanks @eli-b

**Pull request merged**
