### PR TITLE
Improve Cross-Platform Build Instructions in Documentation

### PR DESCRIPTION
**Pull request by Mq-b**
### Description:
This PR updates the build instructions in the documentation to make them more cross-platform and compatible with different development environments, such as Windows with MSVC.

### Details:
Previously, the documentation included commands specific to GNU-based toolchains, notably `make`. However, this can be problematic for users on non-GNU systems (such as Windows with MSVC), where `make` is not available by default. This update replaces `make -j` with the more universally supported `cmake --build . --parallel` and adds a clear `cmake --install .` command for the installation step.

### Reasoning:
- **Cross-Platform Compatibility**: The updated commands are compatible across platforms, as CMake will automatically choose the appropriate build system (e.g., `MSBuild` on Windows, `make` on Unix-like systems).
- **Improved Readability**: By breaking down the commands into separate lines, the process becomes easier to follow, especially for users who are not familiar with the default GNU environment assumptions.
- **Consistent CMake Usage**: Using `cmake --build` and `cmake --install` promotes consistency with CMake’s intended workflows and is less reliant on external toolchains.

---

Thank you for considering this contribution to enhance the usability of the build instructions for a broader range of developers.

### CODE REVIEW

**Comment by gabime** [comment]
Thanks. Could you make it shorter? It takes now 7 lines

**Comment by Mq-b** [comment]
> Thanks. Could you make it shorter? It takes now 7 lines

Thank you for your reply. Okay, I'll do that.

**Comment by Mq-b** [comment]
I compiled the tests in Ubuntu22.04 using gcc11 and windows 11 using the Developer PowerShell for VS 2022 terminal with no problems.

**Comment by Mq-b** [comment]
@gabime

**Comment by gabime** [comment]
using the original && style is better. All is needed is  replacing a single line: the “make build -j” line with cmake —build .”

**Comment by Mq-b** [comment]
> using the original && style is better. All is needed is replacing a single line: the “make build -j” line with cmake —build .”

The problem is that windows powershell terminals don't support this!

**Comment by Mq-b** [comment]
> using the original && style is better. All is needed is replacing a single line: the “make build -j” 

Of course, if you like, of course.

**Comment by SainoNamkho** [comment]
> > using the original && style is better. All is needed is replacing a single line: the “make build -j” line with cmake —build .”
> 
> The problem is that windows powershell terminals don't support this!

Maybe the logical difference counts here. Users may stop copying-pasting commands when one of mutiple lines failed, but with `;` one cannot stop.

In addtion, `;` breaks cmd meanwhile. I personally suggest that a separate powershell version may be honored.

**Comment by gabime** [comment]
Merged. Thanks @Mq-b

**Pull request merged**
