### PR TITLE
cmake: set(CMAKE_POSITION_INDEPENDENT_CODE ON) 

### PR DESCRIPTION
**Pull request by nigels-com**
We're using spdlog as a static library.  On Linux it's necessary to use `-fPIC` flag to link spdlog into shared or executable targets.

### CODE REVIEW

**Comment by gabime** [comment]
This depends on usage.. For example if bulding spdlog as static lib it might be not desirable.

**Comment by nigels-com** [comment]
> This depends on usage.. For example if bulding spdlog as static lib it might be not desirable.

As an opt-in option, then?

**Comment by gabime** [comment]
Yes. Thanks

**Comment by gabime** [comment]
Thanks @nigels-com

**Pull request merged**
