### PR TITLE
Migrate to Github Actions CI

### PR DESCRIPTION
**Pull request by offa**
Adds Github Actions CI and removes (no longer available) Travis CI.

This includes additional builds of latest Clang and GCC version with C++20 enabled.

##### Preparatory work

This is a draft since these two PRs are necessary to get a green build:

- #2498 
- #2499

I'll rebase this PR once these two are merged.

### CODE REVIEW

**Comment by offa** [comment]
PR rebased :+1:

**Comment by gabime** [comment]
Thanks @offa.
The thing is, that I lack the time for learning and/or supporting Actions CI.
If you have the time to support this, it would be great, otherwise I will have to pass.

**Comment by offa** [comment]
Yes, let me know if there's something to do!

**Comment by gabime** [comment]
Well for starters  we need to replace the travis status icon with the Actions CI icon in readme.md

**Comment by offa** [comment]
Seems I have missed that …  :laughing: 

Badge is updated and should become visible once Actions are active on the default branch.

**Comment by gabime** [comment]
Whats the teeks99 line do?

matrix.config.compiler == 'clang' && 'teeks99/clang-ubuntu'

**Comment by offa** [comment]
It selects the `teeks99/clang-ubuntu` docker image on Clang builds. GCC builds use the `gcc` image.

**Comment by gabime** [comment]
why this particular image? seems like  pretty obscure docker image. I hope we can live without it

**Comment by offa** [comment]
Unlike GCC, there's no official Clang image (AFAIK). There are other images around, but that one works quite nice on CI, is based on Ubuntu, provides [almost all version of Clang](https://hub.docker.com/r/teeks99/clang-ubuntu) and is widely used.

> I hope we can live without it

We could, but then we have to do all the work manually. In case where needed version of clang isn't shipped by the Actions runner, it'll become quite an effort.

**Comment by gabime** [comment]
Thanks @offa . Looking good so far.

**Pull request merged**
