### PR TITLE
[issues/2332]clean code, clean up the warning

### PR DESCRIPTION
**Pull request by aengusjiang**
see the issue: https://github.com/gabime/spdlog/issues/2332

### CODE REVIEW

**Comment by gabime** [comment]
This is template instantiation. Not sure  this is the correct fix.

**Comment by gabime** [comment]
I am no expert on this. Are you sure that

```c++
 using q_type = details::mpmc_blocking_queue<item_type>;
```

is also template instantiation ? The cpp doesn't mention this.

**Comment by aengusjiang** [comment]
I sure that will instantiation.

`class SPDLOG_API thread_pool
{
public:
    using item_type = async_msg;
    using q_type = details::mpmc_blocking_queue<item_type>;

    thread_pool(size_t q_max_items, size_t threads_n, std::function<void()> on_thread_start, std::function<void()> on_thread_stop);
    thread_pool(size_t q_max_items, size_t threads_n, std::function<void()> on_thread_start);
    thread_pool(size_t q_max_items, size_t threads_n);

    // message all threads to terminate gracefully and join them
    ~thread_pool();

    thread_pool(const thread_pool &) = delete;
    thread_pool &operator=(thread_pool &&) = delete;

    void post_log(async_logger_ptr &&worker_ptr, const details::log_msg &msg, async_overflow_policy overflow_policy);
    void post_flush(async_logger_ptr &&worker_ptr, async_overflow_policy overflow_policy);
    size_t overrun_counter();
    size_t queue_size();

private:
    q_type q_;

    std::vector<std::thread> threads_;

    void post_async_msg_(async_msg &&new_msg, async_overflow_policy overflow_policy);
    void worker_loop_();

    // process next message in the queue
    // return true if this thread should still be active (while no terminate msg
    // was received)
    bool process_next_msg_();
};`

First, the syntax of using https://en.cppreference.com/w/cpp/language/type_alias
using identifier attr(optional) = type-id 
so the type-id must a definition, not a declaration.

Second, When we define a class, the data member must be have definition, not a declaration.
the alias type q_type  is a member of thread_pool. it must a clear type, or the complier can't work.

**Comment by gabime** [comment]
Thanks @aengusjiang . Merged.

**Pull request merged**
