### PR TITLE
Fix end line

### PR DESCRIPTION
**Pull request by mariuszmaximus**
run on Windows an look at  generated .TXT  https://godbolt.org/z/PYo3Ys8fa

### CODE REVIEW

**Comment by mariuszmaximus** [comment]
Output on console
```
[ffffffff] mem[5f]
0000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

Content in file (on Windows i notepad++)
```
[ffffffff] mem[5f]

0000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

0020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

0040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

0060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

**Comment by gabime** [comment]
\r\n is the standard in windows.

**Comment by mariuszmaximus** [comment]
You have right "\r\n is the standard in windows." 

```
#include <fstream>
int main()
{
    std::ofstream test_CRCF("crcf.txt");
    test_CRCF << "111\n2222";
}
```
In c++ code is only `\n`

But when run on Windows this code wy have `\r\n` in  file.  **It is C++ MAGIC ;)**


Add `\r' in spdlog confuse standard c++ concept

**Comment by gabime** [comment]
thats not magic that the cpp fstream converting. You can open with binary mode to prevent this.

**Pull request closed without merging**
