### PR TITLE
Added CLOCK_MONOTONIC trick

### PR DESCRIPTION
**Pull request by ksergey**
I added new tweak which add ability to use CLOCK_MONOTONIC. It's much faster than CLOCK_REALTIME and more accurate than CLOCK_REALTIME_CORSE.

### CODE REVIEW

**Comment by gabime** [comment]
Thanks, could you add an example entry in tweakme.h and document shortly there ?

**Comment by ksergey** [comment]
Done

**Comment by gabime** [comment]
Thanks for the pull. 
According to https://upvoid.com/devblog/2014/05/linux-timers/ - monotonic is not faster than realtime clock so what is the gain for using it?

**Comment by ksergey** [comment]
My simple benchmark showed me next results (using rdtsc timer): 
```
17:52:26 ✔ ksergey@qf-quorra ~/xdev/build/perf $ ./clock 
realtime: 3848
realtime-coarse: 1004
monotonic: 396
monotonic-raw: 2576
17:52:26 ✔ ksergey@qf-quorra ~/xdev/build/perf $ ./clock 
realtime: 1851
realtime-coarse: 925
monotonic: 344
monotonic-raw: 1508
17:52:27 ✔ ksergey@qf-quorra ~/xdev/build/perf $ ./clock 
realtime: 2156
realtime-coarse: 1032
monotonic: 1000
monotonic-raw: 2424
17:52:28 ✔ ksergey@qf-quorra ~/xdev/build/perf $ ./clock 
realtime: 2484
realtime-coarse: 856
monotonic: 392
monotonic-raw: 2472
17:57:30 ✔ ksergey@qf-quorra ~ $ uname -a 
Linux qf-quorra 4.0.0-pf2 #1 SMP PREEMPT Thu Apr 23 20:48:49 EEST 2015 x86_64 GNU/Linux
```

Looks like I did something wrong.

**Comment by ksergey** [comment]
I updated my benchmark (using for-loops):
```
        const size_t iteration_count = 100000000;

        uint64_t start, duration;

        start = io::performance_clock::start();
        for (size_t i = 0; i < iteration_count; ++i) {
            io::clock< io::ns >::now(CLOCK_REALTIME);
        }
        duration = io::performance_clock::stop() - start;
        std::printf("realtime: %lu\n", duration);

        start = io::performance_clock::start();
        for (size_t i = 0; i < iteration_count; ++i) {
            io::clock< io::ns >::now(CLOCK_REALTIME_COARSE);
        }
        duration = io::performance_clock::stop() - start;
        std::printf("realtime-coarse: %lu\n", duration);

        start = io::performance_clock::start();
        for (size_t i = 0; i < iteration_count; ++i) {
            io::clock< io::ns >::now(CLOCK_MONOTONIC);
        }
        duration = io::performance_clock::stop() - start;
        std::printf("monotonic: %lu\n", duration);

        start = io::performance_clock::start();
        for (size_t i = 0; i < iteration_count; ++i) {
            io::clock< io::ns >::now(CLOCK_MONOTONIC_RAW);
        }
        duration = io::performance_clock::stop() - start;
        std::printf("monotonic-raw: %lu\n", duration);
```

results:
```
18:11:40 ✔ ksergey@qf-quorra ~/xdev/build/perf $ taskset -c 1 ./clock 
realtime: 201526391
realtime-coarse: 48114132
monotonic: 107894272
monotonic-raw: 191289831
18:11:44 ✔ ksergey@qf-quorra ~/xdev/build/perf $ taskset -c 3 ./clock 
realtime: 174854999
realtime-coarse: 47704244
monotonic: 86757050
monotonic-raw: 240060813
18:12:05 ✔ ksergey@qf-quorra ~/xdev/build/perf $ taskset -c 3 ./clock 
realtime: 88721308
realtime-coarse: 25505994
monotonic: 70068950
monotonic-raw: 201485895
18:12:07 ✔ ksergey@qf-quorra ~/xdev/build/perf $ taskset -c 0 ./clock 
realtime: 169116877
realtime-coarse: 45084979
monotonic: 114462974
monotonic-raw: 284702904
18:12:10 ✔ ksergey@qf-quorra ~/xdev/build/perf $ taskset -c 0 ./clock 
realtime: 130881234
realtime-coarse: 37300444
monotonic: 59566023
monotonic-raw: 191377565
18:12:12 ✔ ksergey@qf-quorra ~/xdev/build/perf $ taskset -c 0 ./clock 
realtime: 207558992
realtime-coarse: 45848601
monotonic: 86090304
monotonic-raw: 239045354
```

**Comment by gabime** [comment]
Could it be that the compiler just  eliminates the  ```io::clock< io::ns >::now..);``` lines because its is never used?``` Do you compile with -O2 ?

**Comment by gabime** [comment]
On Gentoo Kernel 3.12.13, Intel i5-2520M realtime takes ~25ns, but in your benchmarks it takes 1ns or 2ns..

Something looks wrong..

**Comment by ksergey** [comment]
looks like CLOCK_MONOTONIC and CLOCK_REALTIME is comparable by speed
```
21:52:21 ✘ ksergey@grave ~/dev/build/perf $ taskset -c 2 ./clock 
realtime:         5608450121
realtime-coarse:  1734460540
monotonic:        5610192694
monotonic-raw:    14982180703
21:52:34 ✔ ksergey@grave ~/dev/build/perf $ taskset -c 2 ./clock 
realtime:         5348384806
realtime-coarse:  1758276870
monotonic:        5172318066
monotonic-raw:    14879798490
21:57:35 ✔ ksergey@grave ~/dev/build/perf $ uname -a 
Linux grave 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux
```

So looks like results depends on kernel. My previous results was on patched kernel (https://pf.natalenko.name).

**Comment by gabime** [comment]
My test also show this.
So I will remove this feature since I see no point..

```c++
#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <chrono>

//#define SPDLOG_CLOCK_COARSE
#define SPDLOG_CLOCK_MONOTONIC

#include "../spdlog/include/spdlog/spdlog.h"


int  main(int argc, char *argv[])
{
        using namespace spdlog::details;
        const size_t iteration_count = 100000000;
        auto now = os::now();
        for(int i = 0; i < iteration_count; ++i)
        {
            auto tp = os::now();          
            if(tp < now)
                std::cout << "Dummy" << std::endl;
        }
        return 0;
}
```
With ```#define SPDLOG_CLOCK_MONOTONIC```:

```
time a.out

real	0m2.039s
user	0m2.036s
sys	0m0.004s
```

Without ```#define SPDLOG_CLOCK_MONOTONIC``` (realtime clock):

```
time a.out

real	0m2.004s
user	0m2.004s
sys	0m0.000s
```

With ```#define COARSE```:

```
time a.out

real	0m0.524s
user	0m0.524s
sys	0m0.000s

```

**Pull request merged**
