### PR TITLE
small std::find conversion

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by gabime** [comment]
Thanks. Please add includes for algorithm and for iterator.

**Comment by neheb** [comment]
Iterator? I think algorithm is enough.

**Comment by neheb** [comment]
Added both.

**Comment by gabime** [comment]
The includes should be  only in the common-inl.h file(so user code not forced to include those  in compiled version)

**Comment by neheb** [comment]
Done. It honestly sounds like a job for iwyu though...

**Comment by gabime** [comment]
Thanks @neheb .

**Pull request merged**
