### PR TITLE
Reduce warnings with pedantic compiler `-Wuseless-cast`

### PR DESCRIPTION
**Pull request by vnepogodin**
on unix systems `getpid` returns `pid_t` which refers to `signed` type same as `int`

### CODE REVIEW

**Comment by gabime** [comment]
how can we be sure it is int in all non win32 platforms?

**Comment by vnepogodin** [comment]
> how can we be sure it is int in all non win32 platforms?

Implement adaptive cast

**Comment by gabime** [comment]
what do you mean?

**Comment by vnepogodin** [comment]
I'll implement that though

**Comment by vnepogodin** [comment]
Well I did implement it

**Comment by vnepogodin** [comment]
also would be nice to add `-Wuseless-cast` for CI/CD with gcc compiler

**Comment by gabime** [comment]
Thanks @vnepogodin

**Pull request merged**
