### PR TITLE
 improve cmake files, option to use clang-tidy while compile 

### PR DESCRIPTION
**Pull request by ClausKlein**
Note:  there is still an issue:

with libfmt @4.1.0 FMT_STRING_VIEW and header is missing! CK  #include <fmt/core.h>

### CODE REVIEW

**Comment by gabime** [comment]
Thanks but doesn't seems to be backwards compatible,hence doesn't pass the tests. Alos there are many un related changes.

**Comment by ClausKlein** [comment]
OK, that is my fault.

  CMake 3.13 or higher is required.  You are running version 3.9.2


But I have 2 questions:

I was not able to build with the current external fmt lib, is this known?

############################
.build/../include/spdlog/logger.h|77 col 18| fatal error: no type named 'memory_buffer' in namespace 'fmt'
||             fmt::memory_buffer buf;

NOTE: new version changed internal interface!
see /opt/local/include/fmt/format.h

namespace internal {

// A memory buffer for trivially copyable/constructible types with the first
// SIZE elements stored in the object itself.
template <typename T, std::size_t SIZE, typename Allocator = std::allocator<T> >
class MemoryBuffer : private Allocator, public Buffer<T> {
...
}
}
###########################

Why creating log directories in that way with a system() call.
IMHO it not better to user std::filesystem?

1: C:\projects\spdlog\tests\test_macros.cpp:11: FAILED:
206 <https://ci.appveyor.com/project/gabime/spdlog/builds/26164037#L206>1: due to unexpected exception with message:
207 <https://ci.appveyor.com/project/gabime/spdlog/builds/26164037#L207>1:   Failed to mkdir -p logs
208 <https://ci.appveyor.com/project/gabime/spdlog/builds/26164037#L208>1: 
209 <https://ci.appveyor.com/project/gabime/spdlog/builds/26164037#L209>1: A subdirectory or file -p already exists.
210 <https://ci.appveyor.com/project/gabime/spdlog/builds/26164037#L210>1: Error occurred while processing: -p.
211 <https://ci.appveyor.com/project/gabime/spdlog/builds/26164037#L211>1: A subdirectory or file logs already exists.
212 <https://ci.appveyor.com/project/gabime/spdlog/builds/26164037#L212>1: Error occurred while processing: logs.
213 <https://ci.appveyor.com/project/gabime/spdlog/builds/26164037#L213>1: -------------------------------------------------------------------------------
214 <https://ci.appveyor.com/project/gabime/spdlog/builds/26164037#L214>

**Comment by tt4g** [comment]
> I was not able to build with the current external fmt lib, is this known?

The version of fmt used by spdlog is 5.3.0:

https://github.com/gabime/spdlog/blob/1cdf09e9dd8929c44e465774460729600f605e79/include/spdlog/fmt/bundled/core.h#L19

I found `fmt::memory_buffer` has been defined since version 5.x.

`fmt::internal::MemoryBuffer` seems to have existed before version 4.x.
Is the version of fmt installed not old?

**Comment by ClausKlein** [comment]
Ops, 
mac ports seems not use an old version:

Thanks, sorry for trouble.

// regards
Claus

Claus-MBP:fmt clausklein$ port info libfmt
libfmt @4.1.0 (devel)
Variants:             debug, (+)universal

Description:          fmt (formerly cppformat) is an open-source formatting library. It can be used as a safe alternative to
                      printf or as a fast alternative to C++ IOStreams.
Homepage:             http://fmtlib.net

Build Dependencies:   cmake
Platforms:            darwin
License:              MIT
Maintainers:          none
Claus-MBP:fmt clausklein$

**Pull request closed without merging**
