### PR TITLE
add udp_sink

### PR DESCRIPTION
**Pull request by vbirds**
add udp_skin support for udp log

### CODE REVIEW

**Comment by vbirds** [comment]
build warning

**Comment by gabime** [comment]
Why did you close this? Seems useful

**Comment by vbirds** [comment]
> Why did you close this? Seems useful

It's been reopened, please check it

**Comment by vbirds** [comment]
> Why did you close this? Seems useful

It's been reopened, please check it

**Comment by gabime** [comment]
Thanks I will. Will take me some time though..
Would appreciate  if you continue actively developing it in the meantime in this branch. 
.

**Comment by kluete** [comment]
fix typo & rename PR to "add udp_sink"? :-)

**Comment by gabime** [comment]
Continued in #2090

**Pull request closed without merging**
