### PR TITLE
Add distributional sink

### PR DESCRIPTION
**Pull request by daersc**
Setting up dist_sink to a logger will inject a layer between the logger and
(some of) it's sinks. Sinks can be added and removed to dist_sink dynamically.

### CODE REVIEW

**Comment by gabime** [comment]
Thanks. It is not fully thread safe though.. The sink_it()or flush() could be called while another thread adds or deletes a sink..

**Comment by daersc** [comment]
Yes you're right. The flush() method was not thread safe. But the _sink_it() method will be invoked by the log() method from base class, which locks the sink, isn't it?

**Comment by gabime** [comment]
yes, but not with the same mutex as the one used to lock the add/remove functions

**Comment by daersc** [comment]
The derived class uses the protected _mutex field from it's base class, so this is the same mutex.

**Comment by gabime** [comment]
Right. My mistake

**Comment by gabime** [comment]
I am not sure what is the use case here..
In what real world scenario would such sink be needed?

**Comment by daersc** [comment]
The use case is to have multiple loggers working on the same sinks (let's say one for stderr and one for a logfile). Now the stderr-sink should be disabled for all loggers.
I could not find an easy way to do this for multiple loggers. Is there any?

**Comment by gabime** [comment]
And how would it be disabled in the proposed solution? Removed  from the dist sink?

**Comment by daersc** [comment]
Yes, this was my intention.

**Comment by gabime** [comment]
ok. will merge. please add some documentarion explaining this (in the wiki please)

**Pull request merged**
