### PR TITLE
fixing pattern_formatter-inl.h(1319): warning C26800: Use of a moved from object: ''user_chars''

### PR DESCRIPTION
**Pull request by wtom76**
following https://github.com/gabime/spdlog/issues/3214#issue-2583804031

### CODE REVIEW

**Comment by gabime** [comment]
Is this a genuine warning? Seems like a false positive

**Comment by tt4g** [comment]
I found a report of a very similar false positive in the Visual Studio developer community: [False positive on code analysis: Warning C26800 "Use of a moved from object with std::map::try\_emplace \- Developer Community](https://developercommunity.visualstudio.com/t/False-positive-on-code-analysis:-Warning/10117317)
It seems to have already been fixed, but is this warning reported in the latest version of Visual Studio?

**Comment by wtom76** [comment]
>  is this warning reported in the latest version of Visual Studio?

Microsoft Visual Studio Community 2022 Version 17.11.5 is latest for today and produces this warning.
std::unique_ptr is guaranteed to be equal to nullptr upon successful move though.
So yes, it's looks like false positive and it's up to you if this PR needed or not.
Thanks! =)

**Comment by gabime** [comment]
Thanks for double checking. Closing.

**Pull request closed without merging**
