### PR TITLE
Fixed SPDLOG_TRACE bug when using a variable for fmt

### LINKED ISSUE #529: SPDLOG_TRACE doesn't compile when given a variable as the `fmt` argument
```
const char* blah = "I am a string";
SPDLOG_TRACE(logger, blah);
```

This fails to compile with the following errors:

```
myfile.cpp: error: expected ‘)’ before ‘blah’
         SPDLOG_TRACE(logger, blah);
                              ^
spdlog/spdlog.h:175:103: note: in definition of macro ‘SPDLOG_TRACE’
   #define SPDLOG_TRACE(logger, ...) logger->trace("[ " __FILE__ ":" SPDLOG_STR_HELPER(__LINE__) " ] " __VA_ARGS__)
                                                                                                       ^~~~~~~~~~~
```

Using the literal explicitly works fine:

```
SPDLOG_TRACE(logger, "I am a string");
```

This compiles without complaint.

Using variables for arguments past the one representing `fmt` also does the job:

```
const char* blah = "I am a string";
SPDLOG_TRACE(logger, "format string {}", blah);
```

This also compiles. It's only when a variable is used as the first argument (besides the logger).

### PR DESCRIPTION
**Pull request by pabloariasal**
Fixes #529

### CODE REVIEW

**Comment by gabime** [comment]
Thanks! I was looking for a way to concat those strings during compile time though (and avoid creating  2 std::stirings on each trace call).  If you coud find such way, it would be great

**Comment by pabloariasal** [comment]
That was in fact my original intention, but had a hard time figuring out how to do this at compile time. I was thinking on the lines of a `constexpr` function but didn't study the possibility further. Concatenating two string literals forced me to either create a temporary char[] (of which size?) or do a malloc (and worry about memory leaks). I decided to use `std::string` given that the `std::string(const char* c)` constructor is very efficient and seemed a lot safer. I made a mistake, though, as the `+` operator in `basic_string` overloads for (std::string, char *), meaning only one instantiation of `std::string` is required and not two. Will give the compile time concatenation some more thoughts.

**Comment by godbyk** [comment]
I took a shot at it, relying on `fmt::format` (which I think uses `constexpr`, but I haven't checked):

```c++
#ifdef SPDLOG_TRACE_ON
#ifdef _MSC_VER
#define SPDLOG_TRACE(logger, s, ...) logger->trace(fmt::format("[ {}({}) ] {}", __FILE__, __LINE__, (s)).c_str(), ##__VA_ARGS__);
#else
#define SPDLOG_TRACE(logger, s, ...) logger->trace(fmt::format("[ {}:{} ] {}", __FILE__, __LINE__, (s)).c_str(), ##__VA_ARGS__);
#endif
#else
#define SPDLOG_TRACE(logger, s, ...)
#endif
```

This is just a first pass. I haven't tested it much yet, but it does work in the following cases:

```c++
SPDLOG_TRACE(console, "a trace message {} {}", 1, 2);
const char* blah = "I am a string and int {}";
SPDLOG_TRACE(console, blah, 0);
const char* blah2 = "Testing string only";
SPDLOG_TRACE(console, blah2);
const std::string blah3 = "Testing std::string only";
SPDLOG_TRACE(console, blah3);
```

Tested with clang++ and g++, but my understanding is that it should work with MSVC, too.

**Comment by gabime** [comment]
@godbyk Looks good,  can you open a PR?

**Comment by gabime** [comment]
Fixed in de595fe2b782763109d9a3b64aaf8b070a7420ed

Thanks@pabloariasal and @godbyk  for your help!

**Pull request closed without merging**
