### PR TITLE
add macros for overriding the individual level names

### PR DESCRIPTION
**Pull request by stevenlunt**
revert the change to add set_string_view and instead add macros to allow the individual level names to be set at compile time

### CODE REVIEW

**Comment by gv-me** [comment]
does this enable setting values from conan? Could you point me to an example?

**Comment by stevenlunt** [comment]
yes.  i also have an update to the recipe

**Comment by stevenlunt** [comment]
in the recipe in conan-center-index, i will add options level_name_debug, etc.  this will set the cmake variable SPDLOG_LEVEL_NAME_DEBUG (defaulting to 'debug').  in CMakeLists.txt in the recipe will add:

target_compile_definitions(spdlog PUBLIC SPDLOG_LEVEL_NAME_DEBUG=\"${SPDLOG_LEVEL_NAME_DEBUG}\")

**Comment by gabime** [comment]
The question is how to use it from cmake regardless of conan.

**Comment by stevenlunt** [comment]
i needed to also add to the CMakeLists.txt.  I pushed that change as well.

built with:

mkdir build && cd build && cmake .. -DSPDLOG_LEVEL_NAME_DEBUG=DBG

**Comment by gabime** [comment]
How about the following. Seems a little cleaner:

```cmake
# ---------------------------------------------------------------------------------------
# Allow override of level names
# ---------------------------------------------------------------------------------------
set(SPDLOG_LEVEL_NAME_TRACE "trace" CACHE STRING "custom level name")
set(SPDLOG_LEVEL_NAME_DEBUG "debug" CACHE STRING "custom level name")
set(SPDLOG_LEVEL_NAME_INFO "info" CACHE STRING "custom level name")
set(SPDLOG_LEVEL_NAME_WARNING "warning" CACHE STRING "custom level name")
set(SPDLOG_LEVEL_NAME_ERROR "error" CACHE STRING "custom level name")
set(SPDLOG_LEVEL_NAME_CRITICAL "critical" CACHE STRING "custom level name")
set(SPDLOG_LEVEL_NAME_OFF "off" CACHE STRING "custom level name")

target_compile_definitions(spdlog PUBLIC SPDLOG_LEVEL_NAME_TRACE=\"${SPDLOG_LEVEL_NAME_TRACE}\")
target_compile_definitions(spdlog PUBLIC SPDLOG_LEVEL_NAME_DEBUG=\"${SPDLOG_LEVEL_NAME_DEBUG}\")
target_compile_definitions(spdlog PUBLIC SPDLOG_LEVEL_NAME_INFO=\"${SPDLOG_LEVEL_NAME_INFO}\")
target_compile_definitions(spdlog PUBLIC SPDLOG_LEVEL_NAME_WARNING=\"${SPDLOG_LEVEL_NAME_WARNING}\")
target_compile_definitions(spdlog PUBLIC SPDLOG_LEVEL_NAME_ERROR=\"${SPDLOG_LEVEL_NAME_ERROR}\")
target_compile_definitions(spdlog PUBLIC SPDLOG_LEVEL_NAME_CRITICAL=\"${SPDLOG_LEVEL_NAME_CRITICAL}\")
target_compile_definitions(spdlog PUBLIC SPDLOG_LEVEL_NAME_OFF=\"${SPDLOG_LEVEL_NAME_OFF}\")
```

**Comment by stevenlunt** [comment]
yes, that is cleaner - thanks

**Comment by gabime** [comment]
Merged. Thanks @stevenlunt

**Comment by stevenlunt** [comment]
thanks

**Pull request merged**
