### PR TITLE
Add .nuspec metadata file 

### PR DESCRIPTION
**Pull request by abdulkareem-siddiq**
Proposal to add the `nuget/gabime.spdlog.nuspec` and `nuget/gabime.spdlog.targets` added to the main repository.
This will allow transparency with respect to the various packages for spdlog in nuget.org.
I'm willing to perform the push to nuget if there is permission to do so from @gabime -- I would not push using my own account.
At least using these files would make it easier to allow users to push to their local nuget repository.
Referencing #2124 and closed/archived: #1149 and #2014.

TO BUILD for local consumption or upload to your private nuget repo:
`nuget.exe pack .\gabime.spdlog.nuspec -Properties VERSION=1.9.2`
This will create gabime.spdlog.1.9.2.nupkg file. You can push this to your local store.
Usage is simple, you #include "spdlog/spdlog.h" etc..

### CODE REVIEW

**Comment by gabime** [comment]
Thanks! However, this is beyond spdlog’s scope. Why not publish directly to nuget.org ?

**Comment by abdulkareem-siddiq** [comment]
I would need your permission to publish using your official name. 
There are quite a few out there and using various versions. 
I posted one using the latest release and since I've been maintaining a private version in our company's repo, I can volunteer to be maintainer for this specific package.

**Comment by abdulkareem-siddiq** [comment]
If you agree then I can publish using our credentials. 
Perhaps we can update the README section on packages.

**Comment by gabime** [comment]
> If you agree then I can publish using our credentials

I don't think you need my agreement to publish under your own credentials.

**Comment by abdulkareem-siddiq** [comment]
My apologies for the misunderstanding but I meant that in order to use 'gabime.spdlog' then I'd need your permission. 
I can use my nuget.org account to publish the package. 
If you like to keep this package official and I humbly request that you agree. 
There are already other publications of spdlog on nuget.org. Some outdated while others don't even follow your versioning.

**Comment by gabime** [comment]
ok, thanks.

**Comment by gabime** [comment]
>in  order to use 'gabime.spdlog'

why do you nee this specific name? can be yours

**Comment by abdulkareem-siddiq** [comment]
> > in  order to use 'gabime.spdlog'
> 
> why do you nee this specific name? can be yours

So for our needs, we already have `spdlog` in our private repository.
My reach-out to you is in order to have an official package (or rather, by owner or authorized party).
You're correct, I can always use `myname.spdlog` but that won't serve the community as an "official" version. 

I'm grateful that you're responsive and taking time out of your schedule to respond to my plea: please accept my offer to maintain the nuget (according to your release schedule and tag) as authorized for the spdlog in nuget.

Thank you.

**Comment by gabime** [comment]
In the time being Im not interested to deal with this even indirectly thru “authorized party”.
If there is a enough demand, I will consider in the future. Thanks anyway for your suggestion, and of course you are welcome to add your scripts to nuget directly.

**Comment by abdulkareem-siddiq** [comment]
> In the time being Im not interested to deal with this even indirectly thru “authorized party”.
> If there is a enough demand, I will consider in the future. Thanks anyway for your suggestion, and of course you are welcome to add your scripts to nuget directly.

Ok. I'll add to nuget.org via my credentials and the generic spdlog without account prefix. Thank you for your time.

**Pull request closed without merging**
