### PR TITLE
Implementation custom flag for pattern formatter

### PR DESCRIPTION
**Pull request by fegomes**
## Requirement
New flag for pattern formatter, example:
`spdlog::set_pattern("%1 %2 %3 %v")`

## Solution
make a unordered_map<char, std::string> and  access methods

## Example
``` cpp
spdlog::set_custom_flag('1', "value1");
spdlog::set_custom_flag('2', "value2");
spdlog::set_custom_flag('3', "value3");
spdlog::set_pattern("%1 %2 %3 %v");
....
```
``` cpp
// ouput : "value1 value2 value3 new message"
logger->info("new message");
```

### CODE REVIEW

**Comment by feklar7** [comment]
Any ETA for this merge request? This is super useful for logging when using ASIO async.

**Comment by gabime** [comment]
@feklar7 Not sure yet. There are several suggestions to add context, each with its own pros and cons. Its in my todo list but no ETA, sorry. 
Why is it useful in particualr in async?

**Comment by kenr** [comment]
@gabime We also have the need for this functionality. Do you have any thoughts about adding this feature?

**Comment by germandiagogomez** [comment]
@gabime same here. I would need this kind of feature.

**Comment by gabime** [comment]
@kenr & @germandiagogomez Please provide example of the intended use. in particular, What kind of flags are needed that cannot be accomplished in current spdlog version ?

**Comment by gabime** [comment]
Implemented. Please see example on how to use.

**Comment by gabime** [comment]
It shoild work. Please provide full example to reproduce

**Comment by MohammadKanan** [comment]
@gabime , appreciate your prompt response
My code is a Qt code ,

```
class my_formatter_flag : public spdlog::custom_flag_formatter
{
public:
    void format(const spdlog::details::log_msg&, const std::tm&, spdlog::memory_buf_t& dest) override
    {
        std::string new_Flag = "custom-flag";
        dest.append(new_Flag.data(), new_Flag.data() + new_Flag.size());
    }

    std::unique_ptr<custom_flag_formatter> clone() const override
    {
        return spdlog::details::make_unique<my_formatter_flag>();
    }
};
        auto currentd = QDate::currentDate().toString("yyyyMMdd");
        using spdlog::details::make_unique; //       
        auto formatter = std::make_unique<spdlog::pattern_formatter>();
        QString pattern = QString("[%1]").arg(currentd);
        formatter->add_flag<my_formatter_flag>('*').set_pattern(pattern.toUtf8().constData());
        spdlog::set_formatter(std::move(formatter));

        //
        auto logger_name = "my_log";
        auto filename = QString("%1/my_log_%2.log").arg(logdir.absolutePath()).arg(suffix);
        auto file_sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>(filename.toUtf8().constData());
        file_sink->set_pattern("[%*] %+");
        auto logger = std::make_shared<spdlog::logger>(logger_name, file_sink);
```

**Comment by MohammadKanan** [comment]
@gabime , I get this output :
`[%*] [2022-03-01 21:38:17.150] [gcs_log] [info] something logged`
while I expect get 
`[20220201] [2022-03-01 21:38:17.150] [gcs_log] [info] something logged`
of course just an example , I am not cascading two dates in my actual log

**Comment by gabime** [comment]
The line 

file_sink->set_pattern("[%*] %+");

is the problem because it doesnt use custom formatter object.

try
 
..

formatter->add_flag<my_formatter_flag>('*').set_pattern(pattern.toUtf8().constData());
auto formatter2 = formatte.clone();
…
file_sink->set_pattern(formatter2);
..

**Comment by MohammadKanan** [comment]
Hello @gabime ,
With
`file_sink->set_pattern(formatter2);`
I get this error
` error: no viable conversion from 'std::unique_ptr<spdlog::formatter>' to 'const std::string' (aka 'const basic_string<char>')`

**Comment by gabime** [comment]
sorry i meant

set_formatter(formatter2)

**Comment by MohammadKanan** [comment]
`error: call to deleted constructor of 'std::unique_ptr<spdlog::formatter>'`

**Comment by MohammadKanan** [comment]
@gabime , running compiled code results in crash , at this last line in hashtable.h
```
// Gets bucket begin, deals with the fact that non-empty buckets contain
      // their before begin node.
      __node_type*
      _M_bucket_begin(size_type __bkt) const;

      __node_type*
      _M_begin() const
      { return static_cast<__node_type*>(_M_before_begin._M_nxt); }
```

**Comment by MohammadKanan** [comment]
@gabime , fixed by rearranging the code , creating file_sink and assigning it's formatter before`spdlog::set_formatter(std::move(formatter));`

**Comment by MohammadKanan** [comment]
@gabime ,
if I call `Logging::createlog("Application closed", CATEGORY::SYSTEM , LOGLEVEL::INFO)`
I Expect to get log 
`[[20220303]] [SYSTEM] Application closed `
but I get 
`[[20220302]] [General] Application closed`

**Comment by MohammadKanan** [comment]
@gabime , Logging::createlog() code is already included above and example call is complemented

**Pull request closed without merging**
