### PR TITLE
[feature] Support dynamic tag setting in android.

### PR DESCRIPTION
**Pull request by lilinxiong**
[feature] Support dynamic tag setting in android.
[change] Modify the Android example, and other examples fail to run error.

Support for dynamically modifying the TAG value in Android is achieved by adding a tag parameter to sink_it_ in base_sink.

### CODE REVIEW

**Comment by lilinxiong** [comment]
Oh~ I'm sorry, I made the modification under Mac yesterday, and forgot to consider win, I will modify it now.

**Comment by gabime** [comment]
Sorry seems there is misunderstanding. All that is needed is to modify a *single* file - the android sink, not anything else.

**Comment by lilinxiong** [comment]
@gabime I tried to modify only android_sink. Although it seems that you can change different TAGs in the log, if you want to use macros (such as obtaining the name of the cpp file, the number of lines, and the name of the function), it is not very convenient. That's why I changed base_sink.

**Comment by lilinxiong** [comment]
After the modification, you can print the log as normal, only ```LOG_INFO("TAG", "code: {0}", 1);``` can print the cpp file name, line number, function name, etc. as before Up.

**Comment by gabime** [comment]
Sorry, too many changes. Closing.

**Comment by lilinxiong** [comment]
Well, it doesn't matter. Thank you for opening up such a great log library.

**Pull request closed without merging**
