### PR TITLE
Fix throwing exception if DYNAMIC_TIME_ZONE_INFORMATION fails

### PR DESCRIPTION
**Pull request by BOOtak**
under windows.

### CODE REVIEW

**Comment by gabime** [comment]
thanks. please use the shorter form and remove sstream.h:
```c++
throw spdlog::spdlog_ex(std::string("Failed gettin..")+GetLastError());
```

**Comment by BOOtak** [comment]
@gabime GetLastError() returns DWORD which is typedef for unsigned int. C++ can't concatenate std::string and int. Instead we can use std::to_string(), so, it will look like
```c++
throw spdlog::spdlog_ex("Failed gettin.." + std::to_string(GetLastError()));
```
Should I edit my code to look line example above?

**Comment by gabime** [comment]
@BOOtak you are right. sorry for the confusion. please use your suggested 

```c++
throw spdlog::spdlog_ex("Failed gettin.." + std::to_string(GetLastError()));
```

**Comment by BOOtak** [comment]
@gabime I've updated my commit, you can merge now

**Pull request merged**
