### PR TITLE
CMakeLists.txt: put GNUInstallDirs after set project language

### PR DESCRIPTION
**Pull request by vitlav**
See also https://gitlab.kitware.com/cmake/cmake/merge_requests/4300

### CODE REVIEW

**Comment by gabime** [comment]
@vitlav What would be the effect on the installed spdlog location after this fix?

**Comment by vitlav** [comment]
> @vitlav What would be the effect on the installed spdlog location after this fix?
.so library will placed to appropriate libdir (/usr/lib64 on biarch system, /usr/lib/x86_64-linux-gnu/ on deb based systems).
libdir in autotools depends on arch.

**Comment by gabime** [comment]
what is biarch system?

**Comment by vitlav** [comment]
> what is biarch system?
Well, a 64 bit Linux system with biarch support does not use /usr/lib for 64 bit libs.
Please check these links:
https://bugzilla.mozilla.org/show_bug.cgi?id=496708
https://lists.gnu.org/archive/html/coreutils/2011-10/msg00057.html

In any case, warning against incorrect using GNUInstallDirs will appear since next cmake major release (3.17).

**Comment by gabime** [comment]
Thx. Merged

**Pull request merged**
