### PR TITLE
remove unreachable code

### PR DESCRIPTION
**Pull request by johannes-schmitt**
Fix for #1748.

### CODE REVIEW

**Review by gabime — COMMENTED** [review]
I think older compiler would complain since throw_spdlog_ex is a function wrapper to throw, (and also this wrapper can be defined as abort())

**Comment by johannes-schmitt** [comment]
I saw
```
#define SPDLOG_THROW(ex)                                                                                     \\
    do                                                                                                       \\
    {                                                                                                        \\
        printf("spdlog fatal error: %s\n", ex.what());                                                       \\
        std::abort();                                                                                        \\
    } while (0)
```
Would it help if the loop-condition would be changed to `while (1)`? I see that not all compilers support the `[[noreturn]]` attribute on `std::abort`. With this, the compiler would understand that any code afterwards is not reachable.

Another possibility would be to disable the compiler warning at the return statement.

I'm obviously missing the bigger picture here, so any help is appreciated.

**Comment by gabime** [comment]
There is no bigger picture :) 
Since we don't call throw directly, compilers might get confused and complain that there is no return statement after the throw_spdlog_ex() call.

**Comment by johannes-schmitt** [comment]
I this case, ignoring the warning for MSVC sounds like a reasonable solution to make compiler happy and avoid any breaking changes for older compilers. PR has been updated accordingly. What do you think?

**Comment by gabime** [comment]
How about adding new boolean “success” variable, and throw at the end if false?

**Pull request closed without merging**
