### PR TITLE
creating an android sinker.

### PR DESCRIPTION
**Pull request by fcoulombe**
https://github.com/gabime/spdlog/issues/48

### CODE REVIEW

**Comment by gabime** [comment]
Thanks..
Why the sink ctor requires unused args like ostream and force flush?
Also, I think that the sink should be just independent sink and not inherited by outstream sink.. Its up to the user to choose the right sink under android

**Comment by fcoulombe** [comment]
I was trying to follow your design.
ostream looked like an interface to output to stdout but i guess that could also mean writing to a file?
gimme a bit and i'll refactor to its own thing

**Comment by joewan** [comment]
Is spdlog support android platform?

**Comment by gabime** [comment]
@joewan no, not oficially, but you can try the android sink in the sinks folder

**Pull request closed without merging**
