### PR TITLE
Updated MIT License

### PR DESCRIPTION
**Pull request by joda01**
Updated to github MIT license to make it accessible by the REST API and project overview

### CODE REVIEW

**Comment by gabime** [comment]
why did you remove the fmt note at the end ?

**Comment by joda01** [comment]
@gabime Hello Gabi, when using a standard license from github it can automatically processed using the github REST API.
By the way, very cool library :)

**Comment by gabime** [comment]
@vitaut Do you have objection of removing the note about fmt lib from of the spdlog license?
Please advise If I should put it somewhere else.

**Comment by vitaut** [comment]
Since {fmt} is included in the repo you should specify that a different license applies to a portion of the code. I have no opinion regarding how it is done.

**Comment by gabime** [comment]
@joda01 The license file seems to be the best place to put additional license info, so I will close this PR.

**Comment by gabime** [comment]
On second thought we could add a license section to readme as recommended [here](https://softwareengineering.stackexchange.com/a/304895)

@joda01 Please add such section to the readme in this PR

**Pull request closed without merging**
