### PR TITLE
Workaround GCC 12 warning

### PR DESCRIPTION
**Pull request by offa**
Building tests on GCC 12 fails due to a false positive in `functional` header:

```
In file included from /usr/local/include/c++/12.2.0/functional:59,
                 from […]/spdlog/tests/catch.hpp:3481,
                 from […]/spdlog/tests/includes.h:3,
                 from […]/spdlog/tests/test_daily_logger.cpp:4:
In constructor 'std::function<_Res(_ArgTypes ...)>::function(std::function<_Res(_ArgTypes ...)>&&) [with _Res = bool; _ArgTypes = {char}]',
    inlined from 'std::__detail::_State<_Char_type>::_State(std::__detail::_State<_Char_type>&&) [with _Char_type = char]' at /usr/local/include/c++/12.2.0/bits/regex_automaton.h:149:4,
    inlined from 'std::__detail::_State<_Char_type>::_State(std::__detail::_State<_Char_type>&&) [with _Char_type = char]' at /usr/local/include/c++/12.2.0/bits/regex_automaton.h:146:7,
    inlined from 'std::__detail::_StateIdT std::__detail::_NFA<_TraitsT>::_M_insert_subexpr_end() [with _TraitsT = std::__cxx11::regex_traits<char>]' at /usr/local/include/c++/12.2.0/bits/regex_automaton.h:290:24:
/usr/local/include/c++/12.2.0/bits/std_function.h:405:42: error: '*(std::function<bool(char)>*)((char*)&__tmp + offsetof(std::__detail::_StateT, std::__detail::_State<char>::<unnamed>.std::__detail::_State_base::<unnamed>)).std::function<bool(char)>::_M_invoker' may be used uninitialized [-Werror=maybe-uninitialized]
  405 |       : _Function_base(), _M_invoker(__x._M_invoker)
      |                                      ~~~~^~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```

- https://github.com/catchorg/Catch2/issues/2423
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105562

### CODE REVIEW

**Comment by gabime** [comment]
Thanks. Perhaps its better to surround with pragma push/pop around the include to catch.hpp instead of disabling this warning globally.

**Comment by offa** [comment]
Indeed, since there's a `include.h` it's a change at one place only. I'll give it a try :+1:.

**Comment by offa** [comment]
PR updated.

**Comment by gabime** [comment]
Thanks @offa

**Pull request merged**
