### PR TITLE
Fix osx build

### LINKED ISSUE #914: OSX: Getting the following error: call to 'count_digits' is ambiguous
Please let me know if a fix if available?

```
XXX/lib/spdlog/include/spdlog/details/pattern_formatter.h:656:35: error: call to 'count_digits' is ambiguous
        const size_t field_size = fmt::internal::count_digits(msg.thread_id);
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
XXX/lib/spdlog/include/spdlog/fmt/bundled/format.h:904:17: note: candidate function
inline unsigned count_digits(uint64_t n) {
                ^
XXX/lib/spdlog/include/spdlog/fmt/bundled/format.h:1009:17: note: candidate function
inline unsigned count_digits(uint32_t n) {
                ^
In file included from XXX/lib/spdlog/include/spdlog/spdlog.h:13:
In file included from XXX/lib/spdlog/include/spdlog/details/registry.h:15:
In file included from XXX/lib/spdlog/include/spdlog/logger.h:23:
In file included from XXX/lib/spdlog/include/spdlog/sinks/sink.h:9:
In file included from XXX/lib/spdlog/include/spdlog/details/pattern_formatter.h:8:
XXX/lib/spdlog/include/spdlog/details/fmt_helper.h:75:19: error: call to 'count_digits' is ambiguous
    auto digits = fmt::internal::count_digits(n);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
XXX/lib/spdlog/include/spdlog/details/fmt_helper.h:94:5: note: in instantiation of function template specialization 'spdlog::details::fmt_helper::pad_uint<unsigned long, 500>' requested here
    pad_uint(n, 6, dest);
    ^
XXX/lib/spdlog/include/spdlog/details/pattern_formatter.h:472:21: note: in instantiation of function template specialization 'spdlog::details::fmt_helper::pad6<unsigned long, 500>' requested here
        fmt_helper::pad6(static_cast<size_t>(micros.count()), dest);
                    ^
XXX/lib/spdlog/include/spdlog/fmt/bundled/format.h:904:17: note: candidate function
inline unsigned count_digits(uint64_t n) {
                ^
XXX/lib/spdlog/include/spdlog/fmt/bundled/format.h:1009:17: note: candidate function
inline unsigned count_digits(uint32_t n) {
                ^
In file included from XXX/lib/spdlog/include/spdlog/spdlog.h:13:
In file included from XXX/lib/spdlog/include/spdlog/details/registry.h:15:
In file included from XXX/lib/spdlog/include/spdlog/logger.h:23:
In file included from XXX/lib/spdlog/include/spdlog/sinks/sink.h:9:
In file included from XXX/lib/spdlog/include/spdlog/details/pattern_formatter.h:8:
/Users/vadimmelnicuk/Developer/c/hazel/lib/spdlog/include/spdlog/details/fmt_helper.h:100:5: error: no matching function for call to 'pad_uint'
    pad_uint(n, 9, dest);
    ^~~~~~~~
XXX/lib/spdlog/include/spdlog/details/pattern_formatter.h:489:21: note: in instantiation of function template specialization 'spdlog::details::fmt_helper::pad9<unsigned long, 500>' requested here
        fmt_helper::pad9(static_cast<size_t>(ns.count()), dest);
                    ^
XXX/lib/spdlog/include/spdlog/details/fmt_helper.h:72:13: note: candidate template ignored: substitution failure [with T = unsigned long, Buffer_Size = 500]
inline void pad_uint(T n, unsigned int width, fmt::basic_memory_buffer<char, Buffer_Size> &dest)
```

### PR DESCRIPTION
**Pull request by DanielChabrowski**
Fixes #914

### CODE REVIEW

**Comment by gabime** [comment]
The thing is, that fmt has an ```fmt::internal::count_digits``` overload that accepts 32bits and might be [faster](https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/fmt/bundled/format.h#L1008) on 32 bits..
Also, what is the cost of converting 32 to 64 bits in 32bit machines?

**Comment by DanielChabrowski** [comment]
> The thing is, that fmt has an `fmt::internal::count_digits` overload that accepts 32bits and might be [faster](https://github.com/gabime/spdlog/blob/v1.x/include/spdlog/fmt/bundled/format.h#L1008) on 32 bits..

Yes, it does and that's the issue. uint64_t and size_t types are different on 64bit mac. The only way I can see to avoid this is to create a function template where uint64_t overload would be chosen if sizeof(size_t) > sizeof(uint32_t), uint32_t otherwise. Do you think that would be better?

https://stackoverflow.com/questions/11603818/why-is-there-ambiguity-between-uint32-t-and-uint64-t-when-using-size-t-on-mac-os

**Comment by gabime** [comment]
Yes. Lets try

**Comment by gabime** [comment]
Looks good. Maybe even another optimization is to
```c++
 using count_type = std::conditional<(sizeof(T) > sizeof(std::uint32_t)), std::uint64_t, std::uint32_t>::type;
```
So that if T is 32 bits wil will use the 32bits overload of fmt::count_digits()

**Pull request merged**
