### PR TITLE
Add tcp_syslog_client_sink

### PR DESCRIPTION
**Pull request by mmarkeloff**
I'm figured out that there is no support for sending messages to remote syslog server, so here it is.

`btw` i'm waiting for #1746 to add UDP support too.

### CODE REVIEW

**Comment by gabime** [comment]
Thanks. PR #1746 was continued in PR #2090 and was merged yesterday.

**Comment by mmarkeloff** [comment]
Now i'm see. But why this PR was closed without merging?

**Comment by gabime** [comment]
Sorry, I am not sure there is enough demand for such sink. I try to avoid an explosion of sinks :)

**Comment by dbotha** [comment]
Aha, I was looking for just this 😅

**Pull request closed without merging**
