### PR TITLE
fixed length and upper case log level tags

### PR DESCRIPTION
**Pull request by asit-dhal**
Hi,

I added the first two enhancement request https://github.com/gabime/spdlog/issues/324  in this PR.

Please check this and let me know if you want something different.

Warm Regards,
Asit

### CODE REVIEW

**Comment by gabime** [comment]
Thanks. I wonder though if it would be better just to provide the option define custom  level names in tweakme.h instead. 

So the user could  define in tweakme.h for example:
```c++
#define SPDLOG_LEVEL_NAMES  { "   TRACE", "   DEBUG", "    INFO",  " WARNING", "   ERROR", "CRITICAL", "OFF" };
```
And to support this common.h would contain:
```c++

#if !defined(SPDLOG_LEVEL_NAMES)
#define SPDLOG_LEVEL_NAMES { "trace", "debug", "info",  "warning", "error", "critical", "off" };
#endif
static const char* level_names[] SPDLOG_LEVEL_NAMES 
```

**Comment by asit-dhal** [comment]
Hi,

It is better than my implementation. I will send a new pull request and with some additional features.

Thanks.

**Comment by Razzeee** [comment]
If you can send the lenth fix in it's own PR, that would be nice. Should hopefully lead to a faster acceptance if there are no other changes involved.

**Comment by asit-dhal** [comment]
Hi,

I will do it today and send you a PR.

**Pull request closed without merging**
