### PR TITLE
Add support for Bazel

### PR DESCRIPTION
**Pull request by Vertexwahn**
This PR helps users of the Bazel build system to integrate `spdlog` in their builds.

In the past it was tried to establish Bazel also as a build system for `spdlog`, but the corresponding [PR](https://github.com/gabime/spdlog/pull/1106) did never went in.

The idea of the [PR](https://github.com/gabime/spdlog/pull/1106) is to make it for users of Bazel as simple as possible to integrate `spdlog`. This would be in my opinion the better solution. I think supporting two build systems (CMake and Bazel) is of course more effort to maintain, but helps to spread `spdlog`.

### CODE REVIEW

**Comment by gabime** [comment]
Thanks. I tried before supporting meson in addition with cmake and it proved problematic and very time consuming to support multiple builds. I suggest open a dedicated repo for this instead.

**Comment by Vertexwahn** [comment]
In your case I would only maintain CMake and do not care about Bazel. Neverthless, I would allow PR that dd Bazel files (e.g. `WORKSPACE.bazel`, `BUILD.bazel`) - what do you fear - in the worst case the Bazel build does simply not work - in the best case someone who uses Bazel can benefit from it. Also other project support CMake and Bazel side by side (e.g. [Catch2](https://github.com/catchorg/Catch2))

**Comment by yesudeep** [comment]
I second this. Bazel has sped up my builds several times and reduced the cognitive overload required to understand the build graph (the dependencies are explicit).

**Comment by gabime** [comment]
Guys you are welcome to create a dedicated repo for this. Takes a few seconds.

**Pull request closed without merging**
