### PR TITLE
Fix runtime when build with -fsanitize=cfi

### PR DESCRIPTION
**Pull request by bansan85**
-flto=thin -fvisibility=hidden -fno-sanitize-trap=cfi

See https://gcc.gnu.org/wiki/Visibility

### CODE REVIEW

**Comment by bansan85** [comment]
I tried to build and run a program with `-fsanitize=cfi` (and `-flto=thin -fvisibility=hidden -fno-sanitize-trap=cfi`) according to the [clang documentation](https://clang.llvm.org/docs/ControlFlowIntegrity.html).

So with this option, all class are by default hidden.

According to [GCC documentation](https://gcc.gnu.org/wiki/Visibility), the _C++ visibility support_ should be `__attribute__ ((visibility ("default")))` for `SPDLOG_API`.

**Comment by bansan85** [comment]
I now have a doubt. Maybe the `__attribute__ ((visibility ("default")))` should not be applied in header_only mode.

**Comment by gabime** [comment]
> I now have a doubt. Maybe the __attribute__ ((visibility ("default"))) should not be applied in header_only mode / static lib.

Yes, need to be careful here not to break backward compatibility.

Here is the closest I could find (I didn't test it. Please make sure it indeed works):

```c++
#ifdef SPDLOG_COMPILED_LIB
#   if defined(SPDLOG_SHARED_LIB) && defined(_WIN32)
#       ifdef spdlog_EXPORTS
#           define SPDLOG_API __declspec(dllexport)
#       else
#           define SPDLOG_API __declspec(dllimport)
#       endif
#   elif defined(SPDLOG_SHARED_LIB) && (defined(__GNUC__) || defined(__clang__))
#       define SPDLOG_API __attribute__((visibility("default")))
#   else // if not SPDLOG_SHARED_LIB or other compiler
#       define SPDLOG_API
#   endif
#   define SPDLOG_INLINE
#   undef SPDLOG_HEADER_ONLY
#else // !defined(SPDLOG_COMPILED_LIB)
#   define SPDLOG_API
#   define SPDLOG_HEADER_ONLY
#   define SPDLOG_INLINE inline
#endif // #ifdef SPDLOG_COMPILED_LIB
```

**Comment by gabime** [comment]
@bansan85 any news on this pr?

**Comment by bansan85** [comment]
Sorry. Thanks for reminding me.

I have to take some time to do it. Give me 14 days so I can make so good tests.

**Comment by gabime** [comment]
@bansan85 Any news?

**Comment by bansan85** [comment]
I'm sorry :confused: I think the code should work but at the current time, I don't have the motivation to write some tests :weary:

**Comment by bansan85** [comment]
I finally took some time to test.

Run the command:

```
/mnt/c/temp/spdlog-1.9.2 # rm -Rf build; cmake -S . -B build -DCMAKE_CXX_COMPILER=clang++ -DSPDLOG_BUILD_SHARED=yes -DCMAKE_CXX_FLAGS="-O3 -flto=thin -fvisibility=hidden -fno-sanitize-trap=cfi"; VERBOSE=1 cmake --build build/ --target all --config Release --parallel
```

**Comment by gabime** [comment]
Thanks @bansan85

**Pull request merged**
